"""add course, facility models

Revision ID: 2be3528c4397
Revises: 8fe3557d7b1f
Create Date: 2026-07-01 15:49:34.045023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be3528c4397'
down_revision: Union[str, Sequence[str], None] = '8fe3557d7b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('facility_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_type', sa.Enum('RESTROOM', 'PARKING', 'LOCKER', 'OTHERS', name='facilitytype'), nullable=False),
    sa.Column('facility_name', sa.String(), nullable=False),
    sa.Column('facility_address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('kakao_place_id', sa.String(), nullable=True),
    sa.Column('place_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('facility_id')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_type', sa.Enum('DRNB', 'CUSTOM', name='coursetype'), nullable=False),
    sa.Column('dmb_id', sa.String(), nullable=True),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'NORMAL', 'HARD', name='difficulty'), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('course_description', sa.Text(), nullable=True),
    sa.Column('sigun', sa.String(), nullable=True),
    sa.Column('brd_div', sa.String(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lng', sa.Float(), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_lng', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('dmb_id')
    )
    op.create_index(op.f('ix_courses_created_by'), 'courses', ['created_by'], unique=False)
    op.create_table('course_facility',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('course_id', 'facility_id')
    )
    op.create_table('course_images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_course_images_course_id'), 'course_images', ['course_id'], unique=False)
    op.create_table('course_waypoints',
    sa.Column('waypoint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('waypoint_id'),
    sa.UniqueConstraint('course_id', 'sequence', name='uq_waypoint_course_sequence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_waypoints')
    op.drop_index(op.f('ix_course_images_course_id'), table_name='course_images')
    op.drop_table('course_images')
    op.drop_table('course_facility')
    op.drop_index(op.f('ix_courses_created_by'), table_name='courses')
    op.drop_table('courses')
    op.drop_table('facilities')
    # ### end Alembic commands ###
