"""add records distance_km snapshot column

Revision ID: 33286b485caf
Revises: 45c3bb5cd05d
Create Date: 2026-09-07 15:13:15.739017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33286b485caf'
down_revision: Union[str, Sequence[str], None] = '45c3bb5cd05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('distance_km', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    # 기존 완주 기록은 스냅샷이 없으므로, 지금 시점의 코스 거리로 한 번 채워둔다
    # (이 이후로 courses.distance가 바뀌어도 이 값은 더 이상 따라 바뀌지 않음)
    op.execute(
        """
        UPDATE records
        SET distance_km = courses.distance
        FROM courses
        WHERE records.course_id = courses.course_id
          AND records.is_completed = true
          AND records.distance_km IS NULL
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'distance_km')
    # ### end Alembic commands ###
