"""add partial index on users.last_login_at for active users

Revision ID: 45c3bb5cd05d
Revises: 97908578de71
Create Date: 2026-09-07 14:39:31.250668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c3bb5cd05d'
down_revision: Union[str, Sequence[str], None] = '97908578de71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_last_login_at_active', 'users', ['last_login_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_last_login_at_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
