"""add banned_accounts.banned_by, unique social_accounts.user_id

Revision ID: 524d965dcb01
Revises: 0e775902eab0
Create Date: 2026-09-03 15:43:41.095836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524d965dcb01'
down_revision: Union[str, Sequence[str], None] = '0e775902eab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banned_accounts', sa.Column('banned_by', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_banned_accounts_banned_by_users', 'banned_accounts', 'users', ['banned_by'], ['user_id']
    )
    op.create_unique_constraint('uq_social_account_user', 'social_accounts', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_social_account_user', 'social_accounts', type_='unique')
    op.drop_constraint(
        'fk_banned_accounts_banned_by_users', 'banned_accounts', type_='foreignkey'
    )
    op.drop_column('banned_accounts', 'banned_by')
    # ### end Alembic commands ###
