"""remove facility place_url column, add kakao_place_id+facility_type unique

Revision ID: 623ea27bc0b3
Revises: 7da40cd26d46
Create Date: 2026-08-02 17:36:22.166560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623ea27bc0b3'
down_revision: Union[str, Sequence[str], None] = '7da40cd26d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 재등록은 create_facility()가 기존 비활성 row 재활성화 방식으로 처리하므로
    # 활성/비활성 구분 없는 일반 unique constraint로 충분함
    op.create_unique_constraint('uq_facility_kakao_place_type', 'facilities', ['kakao_place_id', 'facility_type'])
    op.drop_column('facilities', 'place_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('place_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # place_url은 kakao_place_id로부터 계산 가능한 값이라, 컬럼을 되살릴 때 값도 같이 채워준다
    # (Facility.place_url 프로퍼티의 _KAKAO_PLACE_URL_TEMPLATE과 동일한 형식 — 마이그레이션은
    # 그 시점의 스냅샷이므로 모델을 import하지 않고 URL을 직접 하드코딩)
    op.execute(
        "UPDATE facilities SET place_url = 'https://place.map.kakao.com/' || kakao_place_id "
        "WHERE kakao_place_id IS NOT NULL"
    )
    op.drop_constraint('uq_facility_kakao_place_type', 'facilities', type_='unique')
    # ### end Alembic commands ###
