"""remove facility place_url column, add kakao_place_id+facility_type unique

Revision ID: 623ea27bc0b3
Revises: 7da40cd26d46
Create Date: 2026-08-02 17:36:22.166560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623ea27bc0b3'
down_revision: Union[str, Sequence[str], None] = '7da40cd26d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_facility_kakao_place_type', 'facilities', ['kakao_place_id', 'facility_type'])
    op.drop_column('facilities', 'place_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('place_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_facility_kakao_place_type', 'facilities', type_='unique')
    # ### end Alembic commands ###
