"""add end_sigun to courses

Revision ID: 7299b94313dd
Revises: 33286b485caf
Create Date: 2026-09-09 15:36:01.456238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7299b94313dd'
down_revision: Union[str, Sequence[str], None] = '33286b485caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('end_sigun', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'end_sigun')
    # ### end Alembic commands ###
