"""add banned_accounts table

Revision ID: b076e8f3440e
Revises: 7d76100bab00
Create Date: 2026-08-27 18:50:24.134254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b076e8f3440e'
down_revision: Union[str, Sequence[str], None] = '7d76100bab00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column(
        'provider_type',
        postgresql.ENUM('GOOGLE', 'KAKAO', 'NAVER', name='providertype', create_type=False),
        nullable=False,
    ),
    sa.Column('provider_uid', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('banned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_type', 'provider_uid', name='uq_banned_provider')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banned_accounts')
    # ### end Alembic commands ###
