"""add_total_paused_seconds_to_records

Revision ID: bd2e81b9088b
Revises: 2be3528c4397
Create Date: 2026-07-15 15:08:29.526281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd2e81b9088b'
down_revision: Union[str, Sequence[str], None] = '2be3528c4397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.Column('user_start_lat', sa.Float(), nullable=True),
    sa.Column('user_start_lng', sa.Float(), nullable=True),
    sa.Column('user_end_lat', sa.Float(), nullable=True),
    sa.Column('user_end_lng', sa.Float(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_paused_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_records_course_id'), 'records', ['course_id'], unique=False)
    op.create_index(op.f('ix_records_is_completed'), 'records', ['is_completed'], unique=False)
    op.create_index(op.f('ix_records_user_id'), 'records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_user_id'), table_name='records')
    op.drop_index(op.f('ix_records_is_completed'), table_name='records')
    op.drop_index(op.f('ix_records_course_id'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
