"""banned_accounts에 banned_nickname 컬럼 추가

Revision ID: d19a2922343c
Revises: 33286b485caf
Create Date: 2026-09-09 01:01:08.179304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19a2922343c'
down_revision: Union[str, Sequence[str], None] = '33286b485caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banned_accounts', sa.Column('banned_nickname', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banned_accounts', 'banned_nickname')
    # ### end Alembic commands ###
